#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

# Negative KM => Clockwise Rotation
# Positive KM => Counter Clockwise Rotation

. ${R}etc/init.d/rc.mc_defaults


param set-default MAV_TYPE 13

param set-default MC_PITCHRATE_P 0.0800
param set-default MC_PITCHRATE_I 0.0400
param set-default MC_PITCHRATE_D 0.0010
param set-default MC_PITCH_P 9.0
param set-default MC_ROLLRATE_P 0.0800
param set-default MC_ROLLRATE_I 0.0400
param set-default MC_ROLLRATE_D 0.0010
param set-default MC_ROLL_P 9.0
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_P_ACC 3

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

# Rotor 0
param set-default CA_ROTOR0_PX 0.0
param set-default CA_ROTOR0_PY 1.0
param set-default CA_ROTOR0_PZ 0
param set-default CA_ROTOR0_KM -0.05
# param set-default CA_ROTOR0_AX 0
# param set-default CA_ROTOR0_AY 0
# param set-default CA_ROTOR0_AZ 0

# Rotor 1
param set-default CA_ROTOR1_PX 0.0
param set-default CA_ROTOR1_PY -1.0
param set-default CA_ROTOR1_PZ 0
param set-default CA_ROTOR1_KM 0.05
# param set-default CA_ROTOR1_AX 0
# param set-default CA_ROTOR1_AY 0
# param set-default CA_ROTOR1_AZ 0

# Rotor 2
param set-default CA_ROTOR2_PX 0.866025
param set-default CA_ROTOR2_PY -0.5
param set-default CA_ROTOR2_PZ 0
param set-default CA_ROTOR2_KM 0.05
# param set-default CA_ROTOR2_AX 0
# param set-default CA_ROTOR2_AY 0
# param set-default CA_ROTOR2_AZ 0

# Rotor 3
param set-default CA_ROTOR3_PX -0.866025
param set-default CA_ROTOR3_PY 0.5
param set-default CA_ROTOR3_PZ 0
param set-default CA_ROTOR3_KM -0.05
# param set-default CA_ROTOR3_AX 0
# param set-default CA_ROTOR3_AY 0
# param set-default CA_ROTOR3_AZ 0

# Rotor 4
param set-default CA_ROTOR4_PX 0.866025
param set-default CA_ROTOR4_PY 0.5
param set-default CA_ROTOR4_PZ 0
param set-default CA_ROTOR4_KM 0.05
# param set-default CA_ROTOR4_AX 0
# param set-default CA_ROTOR4_AY 0
# param set-default CA_ROTOR4_AZ 0

# Rotor 5
param set-default CA_ROTOR5_PX -0.866025
param set-default CA_ROTOR5_PY -0.5
param set-default CA_ROTOR5_PZ 0
param set-default CA_ROTOR5_KM -0.05
# param set-default CA_ROTOR5_AX 0
# param set-default CA_ROTOR5_AY 0
# param set-default CA_ROTOR5_AZ 0

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
